# SPDX-FileCopyrightText: 2020, 2021 Alvar Penning
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: CI

on: [push, pull_request]

jobs:
  golang:
    name: Build and test dtn7-go

    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ '1.16' ]

    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build on Go ${{ matrix.go }}
      run: go build ./...

    - name: Test
      run: go test -race ./...


  golangci:
    name: Check golangci-lint

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.37.0
        args: --config contrib/golangci-lint/.golangci.yml


  reuse:
    name: Check REUSE compliance

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@43bd643263f2a557a37e023e538ab9f83dce92a6  # v1.1
